### PR TITLE
feat: fetch and link e-waybill to invoice

### PR DESCRIPTION
**Pull request by rtdany10**
https://github.com/resilient-tech/india-compliance/assets/52111700/f06817c8-5b01-489d-8ffc-4e0a4e15843f

### CODE REVIEW

**Comment by rtdany10** [comment]
Update: Added option to fetch with IRN as well

https://github.com/resilient-tech/india-compliance/assets/52111700/312c11b4-2a1a-474d-93d6-4c308aacf3e2

**Comment by rtdany10** [comment]
@vorasmit :grimacing:

**Comment by rtdany10** [comment]
@vorasmit :grimacing:

**Comment by vorasmit** [comment]
continued in #796 and #798

**Pull request closed without merging**
